from .start import router_start
from .help import router_help
from .user_commands.home import router_home
from .user_commands.about import router_about
from .user_commands.contacts import router_contacts
from .user_commands.catalog import router_catalog
from .admin_commands.admin_panel import router_admin
from .admin_commands.change_info import router_change_info
from .admin_commands.change_catalog import router_admin_catalog
