services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./app:/TelegramBot/app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - network_OT

  db:
    image: postgres:17.5
    container_name: db_postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "YourUser", "-d", "YourDB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - network_OT

networks:
  network_OT:

volumes:
  pg_data:
